version: '2'

services:

  portainer:
    container_name: port1
    image: portainer/portainer
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks: 
    devops:
